# Generated by Django 4.2.7 on 2025-10-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('caja_cerrada', 'Caja Cerrada'), ('combinable', 'Combinable'), ('descuento_porcentaje', 'Descuento Porcentaje'), ('descuento_fijo', 'Descuento Fijo')], max_length=30, verbose_name='Tipo')),
                ('cantidad_minima', models.IntegerField(default=1, help_text='Cantidad mínima de productos para aplicar la promoción', verbose_name='Cantidad Mínima')),
                ('cantidad_exacta', models.IntegerField(blank=True, help_text='Para promociones de caja cerrada', null=True, verbose_name='Cantidad Exacta')),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en porcentaje (ej: 10.00 para 10%)', max_digits=5, null=True, verbose_name='Descuento (%)')),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en valor fijo', max_digits=10, null=True, verbose_name='Descuento Fijo')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='productos.producto', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
