# Generated by Django 4.2.7 on 2025-10-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('terminos', 'Términos y Condiciones'), ('privacidad', 'Política de Privacidad'), ('quienes_somos', '¿Quiénes Somos?'), ('contacto', 'Contacto'), ('faq', 'Preguntas Frecuentes'), ('otro', 'Otro')], max_length=20, unique=True, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Información General',
                'verbose_name_plural': 'Información General',
                'ordering': ['tipo'],
            },
        ),
    ]
