# Generated by Django 5.2.7 on 2025-11-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_listaprecio_remove_producto_precio_lista_3_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lista_precio',
            field=models.ForeignKey(blank=True, help_text='Si no se asigna, usa la lista base sin descuentos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='productos.listaprecio', verbose_name='Lista de Precios'),
        ),
    ]
