# Generated by Django 5.2.7 on 2025-11-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_lista_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que desactivó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se desactivó este registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
    ]
