# Generated by Django 5.2.7 on 2025-12-02 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_eliminado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cuit_dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT/DNI'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='descripcion_ubicacion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de ubicación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='entre_calles',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entre calles'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_zona', to='users.zona', verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='HorarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('horario_apertura', models.TimeField(verbose_name='Horario de apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Horario de cierre')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Horario de Cliente',
                'verbose_name_plural': 'Horarios de Clientes',
                'ordering': ['cliente', 'dia_semana'],
                'unique_together': {('cliente', 'dia_semana')},
            },
        ),
    ]
