# Generated by Django 5.2.7 on 2025-12-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_change_horario_to_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente'), ('transportador', 'Transportador')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
    ]
