# Generated by Django 4.2.7 on 2025-10-28 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0001_initial'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='promociones_aplicadas',
            field=models.ManyToManyField(blank=True, related_name='pedidos', to='promociones.promocion', verbose_name='Promociones Aplicadas'),
        ),
    ]
