# Generated by Django 5.2.7 on 2025-11-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
        ('productos', '0002_listaprecio_remove_producto_precio_lista_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='lista_precio',
            field=models.ForeignKey(blank=True, help_text='Lista de precios aplicada. Null = Lista Base', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='productos.listaprecio', verbose_name='Lista de Precio'),
        ),
    ]
