# Generated by Django 5.2.7 on 2025-11-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado_alter_pedido_lista_precio'),
        ('productos', '0003_alter_producto_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto del pedido. Se establece en NULL si el producto se elimina.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_items', to='productos.producto', verbose_name='Producto'),
        ),
    ]
