# Generated by Django 5.2.7 on 2025-11-16 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_change_producto_to_set_null'),
        ('productos', '0003_alter_producto_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='lista_precio',
            field=models.ForeignKey(blank=True, help_text='Lista de precios aplicada. Null = Lista Base. Se establece en NULL si la lista se elimina.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='productos.listaprecio', verbose_name='Lista de Precio'),
        ),
    ]
