# Generated by Django 5.2.7 on 2025-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_change_lista_precio_to_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='lista_precio_descuento_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Descuento de la lista de precios al momento de crear el pedido', max_digits=5, null=True, verbose_name='Descuento Lista (Snapshot)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lista_precio_nombre_snapshot',
            field=models.CharField(blank=True, help_text='Nombre de la lista de precios al momento de crear el pedido', max_length=100, null=True, verbose_name='Nombre Lista (Snapshot)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='producto_codigo_snapshot',
            field=models.CharField(blank=True, help_text='Código del producto al momento de crear el item', max_length=50, null=True, verbose_name='Código Producto (Snapshot)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='producto_nombre_snapshot',
            field=models.CharField(blank=True, help_text='Nombre del producto al momento de crear el item', max_length=200, null=True, verbose_name='Nombre Producto (Snapshot)'),
        ),
    ]
