# Generated by Django 5.2.7 on 2025-12-21 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_update_estado_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='transportador',
            field=models.ForeignKey(blank=True, help_text='Transportador asignado para entregar este pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Transportador'),
        ),
    ]
