# Generated by Django 5.2.7 on 2025-12-22 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_transportador'),
        ('productos', '0009_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='promocion',
            field=models.ForeignKey(blank=True, help_text='Promoción del pedido. Se establece en NULL si la promoción se elimina.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_items', to='productos.promocion', verbose_name='Promoción'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto_codigo_snapshot',
            field=models.CharField(blank=True, help_text='Código del producto al momento de crear el item (vacío para promociones)', max_length=50, null=True, verbose_name='Código Producto (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto_nombre_snapshot',
            field=models.CharField(blank=True, help_text='Nombre del producto o promoción al momento de crear el item', max_length=200, null=True, verbose_name='Nombre Producto/Promoción (Snapshot)'),
        ),
    ]
