# Generated by Django 5.2.7 on 2025-11-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado sobre el precio base', max_digits=5, verbose_name='Descuento (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Lista de Precio',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_lista_3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_lista_4',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio sin descuentos', max_digits=10, verbose_name='Precio Base'),
            preserve_default=False,
        ),
    ]
