# Generated by Django 5.2.7 on 2025-11-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_listaprecio_remove_producto_precio_lista_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio sin descuentos', max_digits=10, verbose_name='Precio Base'),
        ),
    ]
