# Generated by Django 5.2.7 on 2025-11-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que desactivó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se desactivó este registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que desactivó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se desactivó este registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que desactivó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se desactivó este registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que desactivó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado Por'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se desactivó este registro', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
