# Generated by Django 5.2.7 on 2025-11-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_add_marca_and_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(default='0000000000000', help_text='Código de barras único del producto', max_length=100, unique=True, verbose_name='Código de Barra'),
        ),
    ]
