# Generated by Django 5.2.7 on 2025-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_stock_add_tiene_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url_imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen de la categoría (ej: S3)', null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='url_imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen de la subcategoría (ej: S3)', null=True, verbose_name='URL de Imagen'),
        ),
    ]
