# Generated by Django 5.2.7 on 2025-12-22 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_add_url_imagen_to_categoria_subcategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, help_text='Fecha en que se desactivó este registro', null=True, verbose_name='Fecha de Eliminación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio fijo de la promoción', max_digits=10, verbose_name='Precio')),
                ('url_imagen', models.URLField(blank=True, help_text='URL de la imagen de la promoción (ej: S3)', null=True, verbose_name='URL de Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha desde la cual la promoción está vigente (opcional)', null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha hasta la cual la promoción está vigente (opcional)', null=True, verbose_name='Fecha de Fin')),
                ('eliminado_por', models.ForeignKey(blank=True, help_text='Usuario que desactivó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado Por')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PromocionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de este producto incluida en la promoción', verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_promociones', to='productos.producto', verbose_name='Producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.promocion', verbose_name='Promoción')),
            ],
            options={
                'verbose_name': 'Item de Promoción',
                'verbose_name_plural': 'Items de Promoción',
                'ordering': ['id'],
                'unique_together': {('promocion', 'producto')},
            },
        ),
    ]
